services:
  db:
    image: postgres:14.1-alpine
    container_name: postgresDB 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

    volumes:
      - db:/var/lib/postgresql/data

    networks:
      - host

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    networks:
      - host
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@uq.edu.au
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
  pgadmin-data:

networks:
  host:
